version: 2

sources:
  - name: raw
    description: "Raw landing tables"
    database: analytics
    schema: public
    tables:
      - name: raw_orders
        description: "Raw orders loaded by Airflow"